spring:
  datasource:
    url:jdbc:postgresql://localhost:5432/jwt_security
  spring:
    security:
      user:tharushi
      password:tharushi
    driver-class-name: org.postgresql.Driver
  jpa:
        hibernate:
          ddl-auto: create-drop
        show-sql: true
        properties:
          hibernate:
            format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgresSQLDialect

